[package]
name = "hmac-drbg"
version = "0.1.1"
authors = ["Wei Tang <hi@that.world>"]
description = "Pure Rust implementation of Hmac DRBG."
license = "Apache-2.0"

[dependencies]
digest = "0.6"
generic-array = "0.8"
hmac = "0.4"

[dev-dependencies]
sha2 = "0.6"
etcommon-hexutil = "0.2"
typenum = "1.9"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"